### ISSUE TITLE
Output includes status

### ISSUE THREAD

**Issue by terbolous** [terbolous/statefulset-demo#1]
```
---
metadata:
  creationTimestamp: null
spec:
  selector: null
  serviceName: ""
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers: null
  updateStrategy: {}
status:
  replicas: 0
```
